bot:
  name: MyApiTestApi229Bot
  token: 766124652:AAE5pLpmbob-fHiaDQIvmbS2UbaxNz4x8Dw
#bot description
botInformation: "Описание бота"
#redirect on channel
channel: gosales
#user administration name
adminName: slavanabali

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thingsBotDB
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: logs/app.log