bot:
  name: MyApiTestApi229Bot
  token: 766124652:AAE5pLpmbob-fHiaDQIvmbS2UbaxNz4x8Dw
botInformation: "Повествование, в отличие от описания, представляет собой изображение событий или явлений, совершающихся не одновременно, а следующих друг за другом или обусловливающих друг друга. Самый, по-видимому, краткий в мировой литературе пример текста повествования – знаменитый рассказ Цезаря: «Пришёл, увидел, победил». Он ярко и точно передаёт суть повествования – это рассказ о том, что произошло, случилось."
#redirect on chanel
channel: lentachold
#user administration name
adminName: slavanabali

spring:
  datasource:
    url: jdbc:postgresql://thingsdbserver.postgres.database.azure.com:5432/postgres
    username: things@thingsdbserver
    password: Slavanabali1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: logs/app.log