bot:
  name: sitelist_bot
  token: 689438604:AAFMURUB3uJ67pW79PnSosMDxo0oleqkzo4
#bot description
botInformation: "Описание бота"
#redirect on channel
channel: gosales
#user administration name
adminName: golesha

spring:
  datasource:
    url: jdbc:postgresql://thingsdbserver.postgres.database.azure.com:5432/postgres
    username: things@thingsdbserver
    password: Slavanabali1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: logs/app.log