bot:
  name: MyApiTestApi229Bot
  token: 766124652:AAE5pLpmbob-fHiaDQIvmbS2UbaxNz4x8Dw
botInformation: "Повествование, в отличие от описания, представляет собой изображение событий или явлений, совершающихся не одновременно, а следующих друг за другом или обусловливающих друг друга. Самый, по-видимому, краткий в мировой литературе пример текста повествования – знаменитый рассказ Цезаря: «Пришёл, увидел, победил». Он ярко и точно передаёт суть повествования – это рассказ о том, что произошло, случилось."
#redirect on chanel
channel: lentachold
#user administration name
adminName: slavanabali

spring:
  datasource:
    url: jdbc:postgresql://postgres://pukhtkkyoxbsfd:2ffcfb3fe623632733ebb5a573075b5bbcd365de289f1fb7290f6302db0571b7@ec2-79-125-124-30.eu-west-1.compute.amazonaws.com:5432/d6jiil0qehb868
    username: pukhtkkyoxbsfd
    password: 2ffcfb3fe623632733ebb5a573075b5bbcd365de289f1fb7290f6302db0571b7
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: logs/app.log